version: '3.8'

services:
  radiocalico-dev:
    build: 
      context: .
      target: development
    container_name: radiocalico-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres-dev
      - DB_USER=postgres
      - DB_PASSWORD=dev_password
      - DB_NAME=radiocalico_dev
      - DB_PORT=5432
      - JWT_SECRET=dev-jwt-secret-key
    volumes:
      - .:/app
      - /app/node_modules
      - ./music:/app/music
    depends_on:
      - postgres-dev
    networks:
      - radiocalico-dev-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-dev:
    image: postgres:15-alpine
    container_name: radiocalico-postgres-dev
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=radiocalico_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - radiocalico-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

networks:
  radiocalico-dev-network:
    driver: bridge
